#!/bin/bash

###
#
# Bash Batch Processing script for item extraction
#
# Usage: ./process-batch.sh VENDOR_STRING PDF_DIR CSV_PATH
#
###

echo ""
echo "Batch Processing PDF invoices using $1 vendor profile."
echo ""
echo ""

files=$(ls $2 | grep .pdf)

for file in $files
do
        echo "Extracting $2/$file items to $3"
        trade-invoice-extractor.py -v $1 -i $2/$file -o $3
done